### ISSUE TITLE
ViewCompat.setNestedScrollingEnabled(listView, true);的问题

### ISSUE THREAD

**Issue by axkza** [Mike-bel/MDStudySamples#1]
你好
ViewCompat.setNestedScrollingEnabled(listView, true);
使用上面这句话，还是无法让listview在5.0以下 具有nest的功能，无法联动

**Comment by Mike-bel** [comment]
@axkza 使用 ListView 只能在 Android 5.0 及以上版本中达到nested 效果，5.0 以下不起作用的。
